# Analysis of Different K Values
After playing around with generating quotes, I got curious about how many unique answers could be generated given different k values. It seemed like even for k values that were relatively low, such as 2 or 3, the phrases generated were merely direct quotes rather than being uniquely generated.

## Corpora
I used three different corpora for my testing. The first is just the list of inspirational quotes given in the exercise. The second is the King James Version of the Bible in its entirety because I realized I had it in txt on my computer from a different project a while back. For the third, I was curious how the relative coherentness compared across languages since I speak Spanish, so I included the Reina Valera Bible because it is a large Spanish work in public domain (I thought about Don Quijote, but the Spanish is so archaic it would be hard to tell how distorted it was by the generation). What I downloaded from project Gutenburg turned out to not have the entire text, but it has enough for my purposes, and that gives three different sizes to compare.

In [1]:
import pandas as pd

## Results from Testing
Since building the dictionaries takes some time for the larger works and since the texts are not included in git, I decided the easiest way to present the results would be to save them in a csv that is included, then they can be analyzed in a notebook.

The results for each combination of text and k value show the number of windows/dictionary entries that have a given number of options, ending with 5 or more.

In [2]:
df_results = pd.read_csv('fun_results.csv')
df_results.head()

   Unnamed: 0    text  k  size  1_opt  2_opt  3_opt  4_opt  5+_opt
0           0  quotes  1   794    497    121     60     27      89
1           1  quotes  2  2222   1887    210     50     22      53
2           2  quotes  3  2770   2614    117     22      4      13
3           3  quotes  4  2922   2836     78      5      0       3
4           4  quotes  5  2979   2926     52      0      0       1

To make things more readable and easier to compare with each other, we can add the percentage of the windows with a certain number of options in addition to the raw value.

In [5]:
df_results['1_opt_percent'] = 100 * df_results['1_opt'] / df_results['size']
df_results['2_opt_percent'] = 100 * df_results['2_opt'] / df_results['size']
df_results['3_opt_percent'] = 100 * df_results['3_opt'] / df_results['size']
df_results['4_opt_percent'] = 100 * df_results['4_opt'] / df_results['size']
df_results['5+_opt_percent'] = 100 * df_results['5+_opt'] / df_results['size']
df_results.head()

,Unnamed: 0,text,k,size,1_opt,2_opt,3_opt,4_opt,5+_opt,1_opt_percent,2_opt_percent,3_opt_percent,4_opt_percent,5+_opt_percent
0,0,quotes,1,794,497,121,60,27,89,62.594458,15.239295,7.556675,3.400504,11.209068
1,1,quotes,2,2222,1887,210,50,22,53,84.923492,9.450945,2.250225,0.990099,2.385239
2,2,quotes,3,2770,2614,117,22,4,13,94.368231,4.223827,0.794224,0.144404,0.469314
3,3,quotes,4,2922,2836,78,5,0,3,97.056810,2.669405,0.171116,0.000000,0.102669
4,4,quotes,5,2979,2926,52,0,0,1,98.220879,1.745552,0.000000,0.000000,0.033568